
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 20;
  public static final int CHAR_LIT = 9;
  public static final int NINT_LIT = 5;
  public static final int POWER = 49;
  public static final int MULT = 47;
  public static final int CHAR = 14;
  public static final int BADCHAR = 66;
  public static final int PINT_LIT = 10;
  public static final int INT = 15;
  public static final int NFLOAT_LIT = 7;
  public static final int MINUS = 46;
  public static final int AND = 52;
  public static final int NOT = 51;
  public static final int SEMICOLON = 44;
  public static final int IMPLICATION = 36;
  public static final int LT = 33;
  public static final int RPAR = 59;
  public static final int IN = 55;
  public static final int OR = 53;
  public static final int TDEF = 21;
  public static final int COMMA = 57;
  public static final int NRAT_LIT = 6;
  public static final int BOOL = 13;
  public static final int DIV = 48;
  public static final int RAT = 16;
  public static final int GEQ = 34;
  public static final int PLUS = 45;
  public static final int ASSIGN = 64;
  public static final int MAIN = 2;
  public static final int LOOP_START = 61;
  public static final int DOT = 60;
  public static final int LCRBRA = 39;
  public static final int EOF = 0;
  public static final int PRAT_LIT = 11;
  public static final int RETURN = 30;
  public static final int error = 1;
  public static final int RCRBRA = 40;
  public static final int NULL = 3;
  public static final int MOD = 50;
  public static final int NEQ = 38;
  public static final int END_IF = 25;
  public static final int BREAK = 63;
  public static final int IDENT = 56;
  public static final int PFLOAT_LIT = 12;
  public static final int FDEF = 22;
  public static final int EQ = 37;
  public static final int TOP = 18;
  public static final int LSQBRA = 41;
  public static final int START_IF = 24;
  public static final int DICT = 19;
  public static final int ELSE = 26;
  public static final int READ = 28;
  public static final int QM = 65;
  public static final int RSQBRA = 42;
  public static final int TYPESPEC = 43;
  public static final int FLOAT = 17;
  public static final int THEN = 27;
  public static final int LEQ = 32;
  public static final int BOOL_LIT = 4;
  public static final int LOOP_END = 62;
  public static final int LPAR = 58;
  public static final int LEN = 31;
  public static final int ALIAS = 23;
  public static final int STRING_LIT = 8;
  public static final int GT = 35;
  public static final int DOUBLECOLON = 54;
  public static final int PRINT = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "NULL",
  "BOOL_LIT",
  "NINT_LIT",
  "NRAT_LIT",
  "NFLOAT_LIT",
  "STRING_LIT",
  "CHAR_LIT",
  "PINT_LIT",
  "PRAT_LIT",
  "PFLOAT_LIT",
  "BOOL",
  "CHAR",
  "INT",
  "RAT",
  "FLOAT",
  "TOP",
  "DICT",
  "SEQ",
  "TDEF",
  "FDEF",
  "ALIAS",
  "START_IF",
  "END_IF",
  "ELSE",
  "THEN",
  "READ",
  "PRINT",
  "RETURN",
  "LEN",
  "LEQ",
  "LT",
  "GEQ",
  "GT",
  "IMPLICATION",
  "EQ",
  "NEQ",
  "LCRBRA",
  "RCRBRA",
  "LSQBRA",
  "RSQBRA",
  "TYPESPEC",
  "SEMICOLON",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "POWER",
  "MOD",
  "NOT",
  "AND",
  "OR",
  "DOUBLECOLON",
  "IN",
  "IDENT",
  "COMMA",
  "LPAR",
  "RPAR",
  "DOT",
  "LOOP_START",
  "LOOP_END",
  "BREAK",
  "ASSIGN",
  "QM",
  "BADCHAR"
  };
}

